# Generated by Django 3.2.12 on 2022-03-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220316_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
