# Generated by Django 3.2.12 on 2022-05-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
