# Generated by Django 3.2.12 on 2022-06-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowcart',
            name='bookdate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrowcart',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowcart',
            name='days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='borrowcart',
            name='ip',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='borrowcart',
            name='note',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='borrowcart',
            name='returndate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrowcart',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='borrowcart',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
