# Generated by Django 3.2.12 on 2022-04-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220407_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Read', 'Read'), ('Closed', 'Closed')], max_length=10),
        ),
    ]
